package co.edu.upb.Bounsic;

import java.util.ArrayList;
import java.util.List;

public class BibliotecaCanciones {
	 private List<Cancion> canciones;

     public BibliotecaCanciones() {
             canciones = new ArrayList<Cancion>();
   
             
             // canciones de género "rock"
             canciones.add((Cancion) new Cancion("Bohemian Rhapsody",
                                             "Is this the real life?\r\n"
                                             + "Is this just fantasy?\r\n"
                                             + "Caught in a landside,\r\n"
                                             + "No escape from reality\r\n"
                                             + "Open your eyes,\r\n"
                                             + "Look up to the skies and see,\r\n"
                                             + "I'm just a poor boy, I need no sympathy,\r\n"
                                             + "Because I'm easy come, easy go,\r\n"
                                             + "Little high, little low,\r\n"
                                             + "Any way the wind blows doesn't really matter to\r\n"
                                             + "Me, to me\r\n"
                                             + "\r\n"
                                             + "Mamaaa,\r\n"
                                             + "Just killed a man,\r\n"
                                             + "Put a gun against his head, pulled my trigger,\r\n"
                                             + "Now he's dead\r\n"
                                             + "Mamaaa, life had just begun,\r\n"
                                             + "But now I've gone and thrown it all away\r\n"
                                             + "Mama, oooh,\r\n"
                                             + "Didn't mean to make you cry,\r\n"
                                             + "If I'm not back again this time tomorrow,\r\n"
                                             + "Carry on, carry on as if nothing really matters"
                                             + "\r\n"
                                             + "I see a little silhouetto of a man,\r\n"
                                             + "Scaramouch, Scaramouch, will you do the Fandango!"
                                             + "\r\n"
                                             + "Thunderbolts and lightning, very, very frightening me\r\n"
                                             + "Galileo, Galileo\r\n"
                                             + "Galileo, Galileo\r\n"
                                             + "Galileo, Figaro - magnificoo"
                                             + "\r\n"
                                             + "I'm just a poor boy nobody loves me\r\n"
                                             + "He's just a poor boy from a poor family,\r\n"
                                             + "Spare him his life from this monstrosity\r\n"
                                             + "Easy come, easy go, will you let me go\r\n"
                                             + "Bismillah! No, we will not let you go\r\n"
                                             + "(Let him go!) Bismillah! We will not let you go\r\n"
                                             + "(Let him go!) Bismillah! We will not let you go\r\n"
                                             + "(Let me go) Will not let you go\r\n"
                                             + "(Let me go)(Never) Never let you go\r\n"
                                             + "(Let me go) (Never) let you go (Let me go) Ah\r\n"
                                             + "No, no, no, no, no, no, no\r\n"
                                             + "Oh mama mia, mama mia, mama mia, let me go\r\n"
                                             + "Beelzebub has a devil put aside for me, for me,\r\n"
                                             + "For meee\r\n"
                                             + "\r\n"
                                             + "So you think you can stop me and spit in my eye\r\n"
                                             + "So you think you can love me and leave me to die\r\n"
                                             + "Oh, baby, can't do this to me, baby,\r\n"
                                             + "Just gotta get out, just gotta get right outta here"
                                             + "\r\n"
                                             + "Nothing really matters, Anyone can see,\r\n"
                                             + "Nothing really matters,\r\n"
                                             + "Nothing really matters to me\r\n"
                                             + "Any way the wind blows...", 
                                             
                                             "rock", "Queen"));
             canciones.add((Cancion) new Cancion("Stairway to Heaven",
             		
				                                "There's a lady who's sure\r\n"
				                                + "All that glitters is gold\r\n"
				                                + "And she's buying a stairway to heaven\r\n"
				                                + "When she gets there she knows\r\n"
				                                + "If the stores are all closed\r\n"
				                                + "With a word she can get what she came for"
				                                + "&&"
				                                + "Ooh ooh ooh ooh ooh\r\n"
				                                + "And she's buying a stairway to heaven\r\n"
				                                + "There's a sign on the wall\r\n"
				                                + "But she wants to be sure\r\n"
				                                + "'Cause you know, sometimes words have two meanings\r\n"
				                                + "In a tree by the brook\r\n"
				                                + "There's a songbird who sings\r\n"
				                                + "Sometimes all of our thoughts are misgiven"
				                                + "&&"
				                                + "Ooh, it makes me wonder\r\n"
				                                + "&&"
				                                + "Ooh, it makes me wonder"
				                                + "&&"
				                                + "There's a feeling I get\r\n"
				                                + "When I look to the west\r\n"
				                                + "And my spirit is crying for leaving\r\n"
				                                + "In my thoughts I have seen\r\n"
				                                + "Rings of smoke through the trees\r\n"
				                                + "And the voices of those who stand looking"
				                                + "&&"
				                                + "Ooh, it makes me wonder\r\n"
				                                + "&&"
				                                + "Ooh, it makes me wonder"
				                                + "&&"
				                                + "And it's whispered that soon\r\n"
				                                + "If we all call the tune\r\n"
				                                + "Then the piper will lead us to reason\r\n"
				                                + "And a new day will dawn\r\n"
				                                + "For those who stand long\r\n"
				                                + "And the forests will echo with laughter"
				                                + "&&"
				                                + "Oh whoa-whoa-whoa, oh-oh"
				                                + "&&"
				                                + "If there's a bustle in your hedgerow, don't be alarmed now\r\n"
				                                + "It's just a spring clean for the May Queen\r\n"
				                                + "Yes, there are two paths you can go by, but in the long run\r\n"
				                                + "And there's still time to change the road you're on"
				                                + "&&"
				                                + "And it makes me wonder"
				                                + "&&"
				                                + "Oh, whoa"
				                                + "&&"
				                                + "Your head is humming and it won't go\r\n"
				                                + "In case you don't know\r\n"
				                                + "The piper's calling you to join him"
				                                + "&&"
				                                + "Dear lady, can you hear the wind blow?\r\n"
				                                + "And did you know\r\n"
				                                + "Your stairway lies on the whispering wind?"
				                                + "&&"
				                                + "And as we wind on down the road\r\n"
				                                + "Our shadows taller than our soul\r\n"
				                                + "There walks a lady we all know\r\n"
				                                + "Who shines white light and wants to show\r\n"
				                                + "How everything still turns to gold\r\n"
				                                + "And if you listen very hard\r\n"
				                                + "The tune will come to you at last\r\n"
				                                + "When all are one and one is all, yeah\r\n"
				                                + "To be a rock and not to roll"
				                                + "&&"
				                                + "And she's buying a stairway to heaven",
				                                "rock",
				                                "Led Zeppelin"));
             canciones.add((Cancion) new Cancion("Sweet Child O' Mine",
                             "She's got a smile that it seems to me reminds me of childhood memories"
                             + "She's got a smile that it seems to me\r\n"
                             + "Reminds me of childhood memories\r\n"
                             + "Where everything was as fresh as the bright blue sky\r\n"
                             + "Now and then when I see her face\r\n"
                             + "She takes me away to that special place\r\n"
                             + "And if I stare too long, I'd probably break down and cry"
                             + "&&"
                             + "Whoa, oh, oh\r\n"
                             + "Sweet child o' mine\r\n"
                             + "Whoa, oh, oh, oh\r\n"
                             + "Sweet love of mine"
                             + "&&"
                             + "She's got eyes of the bluest skies\r\n"
                             + "As if they thought of rain\r\n"
                             + "I'd hate to look into those eyes and see an ounce of pain\r\n"
                             + "Her hair reminds me of a warm safe place\r\n"
                             + "Where as a child I'd hide\r\n"
                             + "And pray for the thunder and the rain to quietly pass me by\r\n"
                             + "&&"
                             + "Whoa, oh, oh\r\n"
                             + "Sweet child o' mine\r\n"
                             + "Whoa whoa, oh, oh, oh\r\n"
                             + "Sweet love of mine"
                             + "&&"
                             + "Whoa, yeah\r\n"
                             + "Whoa, oh, oh, oh\r\n"
                             + "Sweet child o' mine\r\n"
                             + "Whoa, oh, whoa, oh\r\n"
                             + "Sweet love of mine\r\n"
                             + "Whoa, oh, oh, oh\r\n"
                             + "Sweet child o' mine\r\n"
                             + "Ooh, yeah\r\n"
                             + "Ooh, sweet love of mine"
                             + "&&"
                             + "Where do we go?\r\n"
                             + "Where do we go now?\r\n"
                             + "Where do we go?\r\n"
                             + "Ooh, oh, where do we go?\r\n"
                             + "Where do we go now?\r\n"
                             + "Oh, where do we go now?\r\n"
                             + "Where do we go? (Sweet child)\r\n"
                             + "Where do we go now?\r\n"
                             + "Ay, ay, ay, ay, ay, ay, ay, ay\r\n"
                             + "Where do we go now?\r\n"
                             + "Ah, ah"
                             + "&&"
                             + "Where do we go?\r\n"
                             + "Oh, where do we go now?\r\n"
                             + "Oh, where do we go?\r\n"
                             + "Oh, where do we go now?\r\n"
                             + "Where do we go?\r\n"
                             + "Oh, where do we go now?\r\n"
                             + "Now, now, now, now, now, now, now\r\n"
                             + "Sweet child\r\n"
                             + "Sweet child of mine", 
                             "rock",
                             "Guns N' Roses"));
             canciones.add((Cancion) new Cancion("Smells Like Teen Spirit", 
             				"Load up on guns, bring your friends\r\n"
             				+ "It's fun to lose and to pretend\r\n"
             				+ "She's over-bored and self-assured\r\n"
             				+ "Oh no, I know a dirty word"
             				+ "&&"
             				+ "Hello, hello, hello, how low\r\n"
             				+ "Hello, hello, hello, how low\r\n"
             				+ "Hello, hello, hello, how low\r\n"
             				+ "Hello, hello, hello"
             				+ "&&"
             				+ "With the lights out, it's less dangerous\r\n"
             				+ "Here we are now, entertain us\r\n"
             				+ "I feel stupid, and contagious\r\n"
             				+ "Here we are now, entertain us\r\n"
             				+ "A mulatto, an albino\r\n"
             				+ "A mosquito, my libido"
             				+ "&&"
             				+ "Yeah, hey, yay"
             				+ "&&"
             				+ "I'm worse at what I do best\r\n"
             				+ "And for this gift, I feel blessed\r\n"
             				+ "Our little group has always been\r\n"
             				+ "And always will until the end"
             				+ "Hello, hello, hello, how low\r\n"
             				+ "Hello, hello, hello, how low\r\n"
             				+ "Hello, hello, hello, how low\r\n"
             				+ "Hello, hello, hello"
             				+ "&&"
             				+ "With the lights out, it's less dangerous\r\n"
             				+ "Here we are now, entertain us\r\n"
             				+ "I feel stupid, and contagious\r\n"
             				+ "Here we are now, entertain us\r\n"
             				+ "A mulatto, an albino\r\n"
             				+ "A mosquito, my libido"
             				+ "&&"
             				+ "Yeah, hey, yay"
             				+ "&&"
             				+ "And I forget, just why I taste\r\n"
             				+ "Oh yeah, I guess it makes me smile\r\n"
             				+ "I found it hard, it's hard to find\r\n"
             				+ "Oh well, whatever, never mind"
             				+ "&&"
             				+ "Hello, hello, hello, how low?\r\n"
             				+ "Hello, hello, hello, how low?\r\n"
             				+ "Hello, hello, hello, how low?\r\n"
             				+ "Hello, hello, hello"
             				+ "&&"
             				+ "With the lights out, it's less dangerous\r\n"
             				+ "Here we are now, entertain us\r\n"
             				+ "I feel stupid, and contagious\r\n"
             				+ "Here we are now, entertain us\r\n"
             				+ "A mulatto, an albino\r\n"
             				+ "A mosquito, my libido"
             				+ "&&"
             				+ "A denial, a denial\r\n"
             				+ "A denial, a denial\r\n"
             				+ "A denial, a denial\r\n"
             				+ "A denial, a denial\r\n"
             				+ "A denial",
                             "rock",
                             "Nirvana"));
             canciones.add((Cancion) new Cancion("Hotel California",
                             "On a dark desert highway\r\n"
                             + "Cool wind in my hair\r\n"
                             + "Warm smell of colitas\r\n"
                             + "Rising up through the air\r\n"
                             + "Up ahead in the distance\r\n"
                             + "I saw a shimmering light\r\n"
                             + "My head grew heavy and my sight grew dim\r\n"
                             + "I had to stop for the night"
                             + "&&"
                             + "There she stood in the doorway\r\n"
                             + "I heard the mission bell\r\n"
                             + "And I was thinking to myself\r\n"
                             + "\"This could be Heaven or this could be Hell\"\r\n"
                             + "Then she lit up a candle\r\n"
                             + "And she showed me the way\r\n"
                             + "There were voices down the corridor\r\n"
                             + "I thought I heard them say"
                             + "&&"
                             + "Welcome to the Hotel California\r\n"
                             + "Such a lovely place (such a lovely place)\r\n"
                             + "Such a lovely face\r\n"
                             + "Plenty of room at the Hotel California\r\n"
                             + "Any time of year (any time of year)\r\n"
                             + "You can find it here"
                             + "&&"
                             + "Her mind is Tiffany-twisted\r\n"
                             + "She got the Mercedes Benz\r\n"
                             + "She got a lot of pretty, pretty boys\r\n"
                             + "That she calls friends\r\n"
                             + "How they dance in the courtyard\r\n"
                             + "Sweet summer sweat\r\n"
                             + "Some dance to remember\r\n"
                             + "Some dance to forget"
                             + "&&"
                             + "So I called up the Captain\r\n"
                             + "\"Please bring me my wine\"\r\n"
                             + "He said, 'We haven't had that spirit here\r\n"
                             + "Since 1969\"\r\n"
                             + "And still those voices are calling from far away\r\n"
                             + "Wake you up in the middle of the night\r\n"
                             + "Just to hear them say"
                             + "&&"
                             + "Welcome to the Hotel California\r\n"
                             + "Such a lovely place (such a lovely place)\r\n"
                             + "Such a lovely face\r\n"
                             + "They livin' it up at the Hotel California\r\n"
                             + "What a nice surprise (what a nice surprise)\r\n"
                             + "Bring your alibis"
                             + "&&"
                             + "Mirrors on the ceiling\r\n"
                             + "The pink champagne on ice\r\n"
                             + "And she said, 'We are all just prisoners here\r\n"
                             + "Of our own device\"\r\n"
                             + "And in the master's chambers\r\n"
                             + "They gathered for the feast\r\n"
                             + "They stab it with their steely knives\r\n"
                             + "But they just can't kill the beast"
                             + "&&"
                             + "Last thing I remember, I was\r\n"
                             + "Running for the door\r\n"
                             + "I had to find the passage back\r\n"
                             + "To the place I was before\r\n"
                             + "\"Relax, \" said the night man\r\n"
                             + "\"We are programmed to receive\r\n"
                             + "You can check out any time you like\r\n"
                             + "But you can never leave\"",
                             "rock", "Eagles"));

             // canciones de género "pop"
             canciones.add((Cancion) new Cancion("Bad Guy", 
             				"White shirt now red, my bloody nose\r\n"
             				+ "Sleepin', you're on your tippy toes\r\n"
             				+ "Creepin' around like no one knows\r\n"
             				+ "Think you're so criminal\r\n"
             				+ "Bruises on both my knees for you\r\n"
             				+ "Don't say thank you or please\r\n"
             				+ "I do what I want when I'm wanting to\r\n"
             				+ "My soul? So cynical"
             				+ "&&"
             				+ "So you're a tough guy\r\n"
             				+ "Like it really rough guy\r\n"
             				+ "Just can't get enough guy\r\n"
             				+ "Chest always so puffed guy\r\n"
             				+ "I'm that bad type\r\n"
             				+ "Make your mama sad type\r\n"
             				+ "Make your girlfriend mad tight\r\n"
             				+ "Might seduce your dad type\r\n"
             				+ "I'm the bad guy, duh&&"
             				+ "&&"
             				+ "I'm the bad guy"
             				+ "&&"
             				+ "I like it when you take control\r\n"
             				+ "Even if you know that you don't\r\n"
             				+ "Own me, I'll let you play the role\r\n"
             				+ "I'll be your animal\r\n"
             				+ "My mommy likes to sing along with me\r\n"
             				+ "But she won't sing this song\r\n"
             				+ "If she reads all the lyrics\r\n"
             				+ "She'll pity the men I know"
             				+ "&&"
             				+ "So you're a tough guy\r\n"
             				+ "Like it really rough guy\r\n"
             				+ "Just can't get enough guy\r\n"
             				+ "Chest always so puffed guy\r\n"
             				+ "I'm that bad type\r\n"
             				+ "Make your mama sad type\r\n"
             				+ "Make your girlfriend mad tight\r\n"
             				+ "Might seduce your dad type\r\n"
             				+ "I'm the bad guy, duh"
             				+ "&&"
             				+ "I'm the bad guy, duh"
             				+ "&&"
             				+ "I'm only good at being bad, bad"
             				+ "&&"
             				+ "I like when you get mad\r\n"
             				+ "I guess I'm pretty glad that you're alone\r\n"
             				+ "You said she's scared of me?\r\n"
             				+ "I mean, I don't see what she sees\r\n"
             				+ "But maybe it's 'cause I'm wearing your cologne"
             				+ "&&"
             				+ "I'm a bad guy\r\n"
             				+ "I'm, I'm a bad guy\r\n"
             				+ "Bad guy, bad guy\r\n"
             				+ "I'm a bad\r\n",
             				"pop",
                             "Billie Eilish"));
             canciones.add((Cancion) new Cancion("Dynamite",
             				"'Cause I-I-I'm in the stars tonight\r\n"
             				+ "So watch me bring the fire and set the night alight"
             				+ "&&"
             				+ "Shoes on, get up in the morn'\r\n"
             				+ "Cup of milk, let's rock and roll\r\n"
             				+ "King Kong, kick the drum, rolling on like a Rolling Stone\r\n"
             				+ "Sing song when I'm walking home\r\n"
             				+ "Jump up to the top, LeBron\r\n"
             				+ "Ding dong, call me on my phone\r\n"
             				+ "Ice tea and a game of ping pong, huh"
             				+ "&&"
             				+ "This is getting heavy\r\n"
             				+ "Can you hear the bass boom? I'm ready (woo hoo)\r\n"
             				+ "Life is sweet as honey\r\n"
             				+ "Yeah, this beat cha-ching like money, huh\r\n"
             				+ "Disco overload, I'm into that, I'm good to go\r\n"
             				+ "I'm diamond, you know I glow up\r\n"
             				+ "Hey, so let's go"
             				+ "&&"
             				+ "'Cause I-I-I'm in the stars tonight\r\n"
             				+ "So watch me bring the fire and set the night alight (hey)\r\n"
             				+ "Shining through the city with a little funk and soul\r\n"
             				+ "So I'ma light it up like dynamite, whoa oh oh"
             				+ "&&"
             				+ "Bring a friend, join the crowd\r\n"
             				+ "Whoever wanna come along\r\n"
             				+ "Word up, talk the talk\r\n"
             				+ "Just move like we off the wall\r\n"
             				+ "Day or night, the sky's alight\r\n"
             				+ "So we dance to the break of dawn\r\n"
             				+ "Ladies and gentlemen, I got the medicine\r\n"
             				+ "So you should keep ya eyes on the ball, huh"
             				+ "&&"
             				+ "This is getting heavy\r\n"
             				+ "Can you hear the bass boom? I'm ready (woo hoo)\r\n"
             				+ "Life is sweet as honey\r\n"
             				+ "Yeah, this beat cha-ching like money\r\n"
             				+ "Disco overload, I'm into that, I'm good to go\r\n"
             				+ "I'm diamond, you know I glow up\r\n"
             				+ "Let's go"
             				+ "&&"
             				+ "'Cause I-I-I'm in the stars tonight\r\n"
             				+ "So watch me bring the fire and set the night alight (hey)\r\n"
             				+ "Shining through the city with a little funk and soul\r\n"
             				+ "So I'ma light it up like dynamite, whoa oh oh"
             				+ "&&"
             				+ "Dy-na-na-na, na-na, na-na-na, na-na-na, life is dynamite\r\n"
             				+ "Dy-na-na-na, na-na, na-na-na, na-na-na, life is dynamite\r\n"
             				+ "Shining through the city with a little funk and soul\r\n"
             				+ "So I'ma light it up like dynamite, whoa oh oh"
             				+ "&&"
             				+ "Dy-na-na-na, na-na, na-na, ayy\r\n"
             				+ "Dy-na-na-na, na-na, na-na, ayy\r\n"
             				+ "Dy-na-na-na, na-na, na-na, ayy\r\n"
             				+ "Light it up like dynamite"
             				+ "&&"
             				+ "Dy-na-na-na, na-na, na-na, ayy\r\n"
             				+ "Dy-na-na-na, na-na, na-na, ayy\r\n"
             				+ "Dy-na-na-na, na-na, na-na, ayy\r\n"
             				+ "Light it up like dynamite"
             				+ "&&"
             				+ "'Cause I-I-I'm in the stars tonight\r\n"
             				+ "So watch me bring the fire and set the night alight\r\n"
             				+ "Shining through the city with a little funk and soul\r\n"
             				+ "So I'ma light it up like dynamite (this is ah)"
             				+ "&&"
             				+ "'Cause I-I-I'm in the stars tonight\r\n"
             				+ "So watch me bring the fire and set the night alight (alight, oh)\r\n"
             				+ "Shining through the city with a little funk and soul\r\n"
             				+ "So I'ma light it up like dynamite, whoa (light it up like dynamite)"
             				+ "&&"
             				+ "Dy-na-na-na, na-na, na-na-na, na-na-na, life is dynamite\r\n"
             				+ "Dy-na-na-na, na-na, na-na-na, na-na-na, life is dynamite\r\n"
             				+ "Shining through the city with a little funk and soul\r\n"
             				+ "So I'ma light it up like dynamite, whoa oh oh", 
             				"pop",
             				"BTS"));
             canciones.add((Cancion) new Cancion("Watermelon Sugar", 
             				"Tastes like strawberries\r\n"
             				+ "On a summer evenin'\r\n"
             				+ "And it sounds just like a song"
             				+ "&&"
             				+ "I want more berries\r\n"
             				+ "And that summer feelin'\r\n"
             				+ "It's so wonderful and warm"
             				+ "&&"
             				+ "Breathe me in\r\n"
             				+ "Breathe me out\r\n"
             				+ "I don't know if I could ever go without\r\n"
             				+ "I'm just thinking out loud\r\n"
             				+ "I don't know if I could ever go without"
             				+ "&&"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar high\r\n"
             				+ "Watermelon sugar"
             				+ "&&"
             				+ "Strawberries\r\n"
             				+ "On a summer evenin'\r\n"
             				+ "Baby, you're the end of June"
             				+ "&&"
             				+ "I want your belly\r\n"
             				+ "And that summer feelin'\r\n"
             				+ "Getting washed away in you"
             				+ "&&"
             				+ "Breathe me in\r\n"
             				+ "Breathe me out\r\n"
             				+ "I don't know if I could ever go without"
             				+ "&&"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar high"
             				+ "&&"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar high"
             				+ "&&"
             				+ "I just wanna taste it\r\n"
             				+ "I just wanna taste it\r\n"
             				+ "Watermelon sugar high"
             				+ "&&"
             				+ "Tastes like strawberries\r\n"
             				+ "On a summer evenin'\r\n"
             				+ "And it sounds just like a song"
             				+ "&&"
             				+ "I want your belly\r\n"
             				+ "And that summer feelin'\r\n"
             				+ "I don't know if I could ever go without"
             				+ "&&"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar (sugar)\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar high (sugar)"
             				+ "&&"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar\r\n"
             				+ "High\r\n"
             				+ "Watermelon sugar high"
             				+ "&&"
             				+ "I just wanna taste it\r\n"
             				+ "I just wanna taste it\r\n"
             				+ "Watermelon sugar high"
             				+ "&&"
             				+ "I just wanna taste it\r\n"
             				+ "I just wanna taste it\r\n"
             				+ "Watermelon sugar high\r\n"
             				+ "Watermelon sugar",
                             "pop",
                             "Harry Styles"));
             canciones.add((Cancion) new Cancion("Shape of You",
                                             "The club isn't the best place to find a lover\r\n"
                                             + "So the bar is where I go\r\n"
                                             + "Me and my friends at the table doing shots\r\n"
                                             + "Drinking fast and then we talk slow\r\n"
                                             + "Come over and start up a conversation with just me\r\n"
                                             + "And trust me I'll give it a chance now\r\n"
                                             + "Take my hand, stop, put Van the Man on the jukebox\r\n"
                                             + "And then we start to dance, and now I'm singing like"
                                             + "&&"
                                             + "Girl, you know I want your love\r\n"
                                             + "Your love was handmade for somebody like me\r\n"
                                             + "Come on now, follow my lead\r\n"
                                             + "I may be crazy, don't mind me\r\n"
                                             + "Say, boy, let's not talk too much\r\n"
                                             + "Grab on my waist and put that body on me\r\n"
                                             + "Come on now, follow my lead\r\n"
                                             + "Come, come on now, follow my lead"
                                             + "&&"
                                             + "I'm in love with the shape of you\r\n"
                                             + "We push and pull like a magnet do\r\n"
                                             + "Although my heart is falling too\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "Last night you were in my room\r\n"
                                             + "And now my bedsheets smell like you\r\n"
                                             + "Every day discovering something brand new\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "(Oh-I-oh-I-oh-I-oh-I)\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "(Oh-I-oh-I-oh-I-oh-I)\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "(Oh-I-oh-I-oh-I-oh-I)\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "Every day discovering something brand new\r\n"
                                             + "I'm in love with the shape of you"
                                             + "&&"
                                             + "One week in we let the story begin\r\n"
                                             + "We're going out on our first date\r\n"
                                             + "You and me are thrifty, so go all you can eat\r\n"
                                             + "Fill up your bag and I fill up a plate\r\n"
                                             + "We talk for hours and hours about the sweet and the sour\r\n"
                                             + "And how your family is doing okay\r\n"
                                             + "Leave and get in a taxi, then kiss in the backseat\r\n"
                                             + "Tell the driver make the radio play, and I'm singing like"
                                             + "&&"
                                             + "Girl, you know I want your love\r\n"
                                             + "Your love was handmade for somebody like me\r\n"
                                             + "Come on now, follow my lead\r\n"
                                             + "I may be crazy, don't mind me\r\n"
                                             + "Say, boy, let's not talk too much\r\n"
                                             + "Grab on my waist and put that body on me\r\n"
                                             + "Come on now, follow my lead\r\n"
                                             + "Come, come on now, follow my lead"
                                             + "&&"
                                             + "I'm in love with the shape of you\r\n"
                                             + "We push and pull like a magnet do\r\n"
                                             + "Although my heart is falling too\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "Last night you were in my room\r\n"
                                             + "And now my bedsheets smell like you\r\n"
                                             + "Every day discovering something brand new\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "(Oh-I-oh-I-oh-I-oh-I)\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "(Oh-I-oh-I-oh-I-oh-I)\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "(Oh-I-oh-I-oh-I-oh-I)\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "Every day discovering something brand new\r\n"
                                             + "I'm in love with the shape of you"
                                             + "&&"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on, be my baby, come on"
                                             + "&&"
                                             + "I'm in love with the shape of you\r\n"
                                             + "We push and pull like a magnet do\r\n"
                                             + "Although my heart is falling too\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "Last night you were in my room\r\n"
                                             + "And now my bedsheets smell like you\r\n"
                                             + "Every day discovering something brand new\r\n"
                                             + "I'm in love with your body\r\n"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on (I'm in love with your body), be my baby, come on\r\n"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on (I'm in love with your body), be my baby, come on\r\n"
                                             + "Come on, be my baby, come on\r\n"
                                             + "Come on (I'm in love with your body), be my baby, come on\r\n"
                                             + "Every day discovering something brand new\r\n"
                                             + "I'm in love with the shape of you",
                                             "pop",
                                             "Ed Sheeran"));
             canciones.add((Cancion) new Cancion("Blinding Lights",
                             "I've been tryna call\r\n"
                             + "I've been on my own for long enough\r\n"
                             + "Maybe you can show me how to love, maybe\r\n"
                             + "I'm going through withdrawals\r\n"
                             + "You don't even have to do too much\r\n"
                             + "You can turn me on with just a touch, baby"
                             + "&&"
                             + "I look around and\r\n"
                             + "Sin City's cold and empty (oh)\r\n"
                             + "No one's around to judge me (oh)\r\n"
                             + "I can't see clearly when you're gone"
                             + "&&"
                             + "I said, ooh, I'm blinded by the lights\r\n"
                             + "No, I can't sleep until I feel your touch\r\n"
                             + "I said, ooh, I'm drowning in the night\r\n"
                             + "Oh, when I'm like this, you're the one I trust\r\n"
                             + "(Hey, hey, hey)"
                             + "&&"
                             + "I'm running out of time\r\n"
                             + "'Cause I can see the sun light up the sky\r\n"
                             + "So I hit the road in overdrive, baby, oh"
                             + "&&"
                             + "The city's cold and empty (oh)\r\n"
                             + "No one's around to judge me (oh)\r\n"
                             + "I can't see clearly when you're gone"
                             + "&&"
                             + "I said, ooh, I'm blinded by the lights\r\n"
                             + "No, I can't sleep until I feel your touch\r\n"
                             + "I said, ooh, I'm drowning in the night\r\n"
                             + "Oh, when I'm like this, you're the one I trust\r\n"
                             + "&&"
                             + "I'm just walking by to let you know (by to let you know)\r\n"
                             + "I can never say it on the phone (say it on the phone)\r\n"
                             + "Will never let you go this time (ooh)"
                             + "&&"
                             + "I said, ooh, I'm blinded by the lights\r\n"
                             + "No, I can't sleep until I feel your touch\r\n"
                             + "(Hey, hey, hey)"
                             + "&&"
                             + "I said, ooh, I'm blinded by the lights\r\n"
                             + "No, I can't sleep until I feel your touch", 
                             "pop",
                             "The Weeknd"));

             // canciones de género "hip hop"
             canciones.add((Cancion) new Cancion("Lose Yourself",
                                             "Look\r\n"
                                             + "If you had\r\n"
                                             + "One shot\r\n"
                                             + "Or one opportunity\r\n"
                                             + "To seize everything you ever wanted\r\n"
                                             + "In one moment\r\n"
                                             + "Would you capture it\r\n"
                                             + "Or just let it slip?"
                                             + "&&"
                                             + "Yo\r\n"
                                             + "His palms are sweaty, knees weak, arms are heavy\r\n"
                                             + "There's vomit on his sweater already, mom's spaghetti\r\n"
                                             + "He's nervous, but on the surface he looks calm and ready\r\n"
                                             + "To drop bombs, but he keeps on forgettin'\r\n"
                                             + "What he wrote down, the whole crowd goes so loud\r\n"
                                             + "He opens his mouth, but the words won't come out\r\n"
                                             + "He's chokin', how, everybody's jokin' now\r\n"
                                             + "The clocks run out, times up, over, blaow\r\n"
                                             + "Snap back to reality, ope there goes gravity\r\n"
                                             + "Ope, there goes Rabbit, he choked\r\n"
                                             + "He's so mad, but he won't give up that easy? No\r\n"
                                             + "He won't have it, he knows his whole back's to these ropes\r\n"
                                             + "It don't matter, he's dope, he knows that, but he's broke\r\n"
                                             + "He's so stagnant, he knows, when he goes back to this mobile home, that's when it's\r\n"
                                             + "Back to the lab again, yo, this whole rhapsody\r\n"
                                             + "Better go capture this moment and hope it don't pass him"
                                             + "&&"
                                             + "You better lose yourself in the music, the moment\r\n"
                                             + "You own it, you better never let it go\r\n"
                                             + "You only get one shot, do not miss your chance to blow\r\n"
                                             + "This opportunity comes once in a lifetime"
                                             + "&&"
                                             + "You better lose yourself in the music, the moment\r\n"
                                             + "You own it, you better never let it go\r\n"
                                             + "You only get one shot, do not miss your chance to blow\r\n"
                                             + "This opportunity comes once in a lifetime\r\n"
                                             + "You better"
                                             + "&&"
                                             + "His soul's escaping, through this hole that is gaping\r\n"
                                             + "This world is mine for the taking\r\n"
                                             + "Make me king, as we move toward a New World Order\r\n"
                                             + "A normal life is borin', but super stardom's close to post mortem\r\n"
                                             + "It only grows harder, only grows hotter\r\n"
                                             + "He blows, it's all over, these hoes is all on him\r\n"
                                             + "Coast to coast shows, he's known as the Globetrotter\r\n"
                                             + "Lonely roads, God only knows, he's grown farther from home, he's no father\r\n"
                                             + "He goes home and barely knows his own daughter\r\n"
                                             + "But hold your nose 'cause here goes the cold water\r\n"
                                             + "These hoes don't want him no mo', he's cold product\r\n"
                                             + "They moved on to the next schmo who flows, he nose dove and sold nada\r\n"
                                             + "So the soap opera is told and unfolds, I suppose it's old partna, but the beat goes on\r\n"
                                             + "Da-da-dum, da-dum, da-da"
                                             + "&&"
                                             + "You better lose yourself in the music, the moment\r\n"
                                             + "You own it, you better never let it go\r\n"
                                             + "You only get one shot, do not miss your chance to blow\r\n"
                                             + "This opportunity comes once in a lifetime"
                                             + "&&"
                                             + "You better lose yourself in the music, the moment\r\n"
                                             + "You own it, you better never let it go\r\n"
                                             + "You only get one shot, do not miss your chance to blow\r\n"
                                             + "This opportunity comes once in a lifetime\r\n"
                                             + "You better"
                                             + "&&"
                                             + "No more games, I'ma change what you call rage\r\n"
                                             + "Tear this motherfuckin' roof off like two dogs caged\r\n"
                                             + "I was playin' in the beginnin', the mood all changed\r\n"
                                             + "I been chewed up and spit out and booed off stage\r\n"
                                             + "But I kept rhymin' and stepped right in the next cypher\r\n"
                                             + "Best believe somebody's payin' the Pied Piper\r\n"
                                             + "All the pain inside amplified by the\r\n"
                                             + "Fact that I can't get by with my nine to\r\n"
                                             + "Five and I can't provide the right type of\r\n"
                                             + "Life for my family 'cause man, these goddamn food stamps don't buy diapers\r\n"
                                             + "And its no movie, there's no Mekhi Phifer\r\n"
                                             + "This is my life and these times are so hard\r\n"
                                             + "And it's getting even harder tryna feed and water my seed, plus\r\n"
                                             + "Teeter totter, caught up between bein' a father and a prima donna\r\n"
                                             + "Baby mama drama, screamin' on her, too much\r\n"
                                             + "For me to wanna stay in one spot, another day of monotony's\r\n"
                                             + "Gotten me to the point, I'm like a snail I've got\r\n"
                                             + "To formulate a plot or end up in jail or shot\r\n"
                                             + "Success is my only motherfuckin' option, failure's not\r\n"
                                             + "Mom, I love you, but this trailer's got to go, I cannot grow old in Salem's Lot\r\n"
                                             + "So here I go, is my shot\r\n"
                                             + "Feet, fail me not, this may be the only opportunity that I got"
                                             + "&&"
                                             + "You better lose yourself in the music, the moment\r\n"
                                             + "You own it, you better never let it go\r\n"
                                             + "You only get one shot, do not miss your chance to blow\r\n"
                                             + "This opportunity comes once in a lifetime"
                                             + "&&"
                                             + "You better lose yourself in the music, the moment\r\n"
                                             + "You own it, you better never let it go\r\n"
                                             + "You only get one shot, do not miss your chance to blow\r\n"
                                             + "This opportunity comes once in a lifetime\r\n"
                                             + "You better"
                                             + "&&"
                                             + "You can do anything you set your mind to, man",
                                             "hip hop", "Eminem"));
             canciones.add((Cancion) new Cancion("Nuthin' But a G Thang",
             				"One, two, three and to the fo'\r\n"
             				+ "Snoop Doggy Dogg and Dr. Dre is at the do'\r\n"
             				+ "Ready to make an entrance, so back on up\r\n"
             				+ "'Cause you know we're 'bout to rip, shit up\r\n"
             				+ "Gimme the microphone first, so I can bust like a bubble\r\n"
             				+ "Compton and Long Beach together, now you know you in trouble\r\n"
             				+ "Ain't nuttin' but a G thang, baby, two loc'ed out niggaz so we're crazy"
             				+ "&&"
             				+ "Death Row is the label that pays me\r\n"
             				+ "Unfadeable, so please don't try to fade this (hell, yeah)\r\n"
             				+ "But uhh, back to the lecture at hand\r\n"
             				+ "Perfection is perfected, so I'ma let 'em understand\r\n"
             				+ "From a young G's perspective and before me dig out\r\n"
             				+ "A bitch I have to find a contraceptive\r\n"
             				+ "You never know she could be earnin' her man\r\n"
             				+ "And learnin' her man and at the same time burnin' her man"
             				+ "&&"
             				+ "Now, you know I ain't with that shit, Lieutenant\r\n"
             				+ "Ain't no pussy good enough to get burnt while I'm up in it (yeah)\r\n"
             				+ "And that's realer than real deal Holyfield\r\n"
             				+ "And now you hookers and hoes know how I feel\r\n"
             				+ "Well, if it's good enough to get broke off a proper chunk\r\n"
             				+ "I'll take a small piece of some of that funky stuff"
             				+ "&&"
             				+ "It's like this, and like that, and like this, and uh\r\n"
             				+ "It's like that, and like this, and like that, and uh\r\n"
             				+ "It's like this, and like that, and like this, and uh"
             				+ "&&"
             				+ "Dre, creep to the mic like a phantom"
             				+ "&&"
             				+ "Well, I'm peepin', and I'm creepin', and I'm creepin'\r\n"
             				+ "But I damn near got caught, 'cause my beeper kept beepin'\r\n"
             				+ "Now, it's time for me to make my impression felt\r\n"
             				+ "So, sit back, relax, and strap on your seatbelt"
             				+ "&&"
             				+ "You never been on a ride like this before\r\n"
             				+ "With a producer who can rap and control the maestro\r\n"
             				+ "At the same time with the dope rhyme that I kick\r\n"
             				+ "You know, and I know, I flow some old funky shit"
             				+ "&&"
             				+ "To add to my collection, the selection\r\n"
             				+ "Symbolizes dope, take a toke, but don't choke\r\n"
             				+ "If you do, you'll have no clue\r\n"
             				+ "On what me and my homey Snoop Dogg came to do"
             				+ "&&"
             				+ "It's like this, and like that, and like this, and uh\r\n"
             				+ "It's like that, and like this, and like that, and uh\r\n"
             				+ "It's like this, and who gives a fuck about those?\r\n"
             				+ "So just chill, 'til the next episode"
             				+ "&&"
             				+ "You've got the feeling\r\n"
             				+ "Rock the other side\r\n"
             				+ "You've got the feeling (yeah, yeah)"
             				+ "Fallin' back on that ass with a hellafied gangsta lean\r\n"
             				+ "Gettin' funky on the mic like a old batch of collard greens\r\n"
             				+ "It's the capital S, oh yes, I'm fresh, N double O-P\r\n"
             				+ "D-O double G-Y, D-O double G, ya see\r\n"
             				+ "Showin' much flex when it's time to wreck a mic\r\n"
             				+ "Pimpin' hoes and clockin' a grip like my name was Dolomite\r\n"
             				+ "Yeah, and it don't quit, I think they in the mood for some motherfuckin' G shit\r\n"
             				+ "(Hell, yeah)"
             				+ "&&"
             				+ "So, Dre\r\n"
             				+ "(Wud up, Dogg?)\r\n"
             				+ "Gotta give 'em what they want\r\n"
             				+ "(What's that, G?)\r\n"
             				+ "We gotta break em off somethin'\r\n"
             				+ "(Hell, yeah)\r\n"
             				+ "And it's gotta be bumpin'\r\n"
             				+ "City of Compton"
             				+ "&&"
             				+ "It's where it takes place so when asked, yo' attention\r\n"
             				+ "Mobbin' like a muh'fucker but I ain't lynchin'\r\n"
             				+ "Droppin' the funky shit that's makin' the sucka niggaz mumble\r\n"
             				+ "When I'm on the mic, it's like a cookie they all crumble\r\n"
             				+ "Try to get close, and your ass'll get smacked\r\n"
             				+ "My motherfuckin' homie Doggy Dogg has got my back\r\n"
             				+ "Never let me slip, 'cause if I slip, then I'm slippin'\r\n"
             				+ "But if I got my nina, then you know I'm straight trippin'"
             				+ "&&"
             				+ "And I'ma continue to put the rap down, put the Mack down\r\n"
             				+ "And if you bitches talk shit, I'll have to put the smack down\r\n"
             				+ "Yeah, and you don't stop, I told you I'm just like a clock\r\n"
             				+ "When I tick and I tock, but I'm never off\r\n"
             				+ "Always on to the break of dawn, C-O-M-P-T-O-N\r\n"
             				+ "And the city they call Long Beach, puttin' the shit together\r\n"
             				+ "Like my nigga D-O-C, no one can do it better\r\n"
             				+ "&&"
             				+ "Like this, that, and this, and uh\r\n"
             				+ "It's like that, and like this, and like that, and uh\r\n"
             				+ "It's like this, and who gives a fuck about those?\r\n"
             				+ "So just chill, 'til the next episode"
             				+ "&&"
             				+ "You've got the feeling\r\n"
             				+ "Rock the other side\r\n"
             				+ "You've got the feeling (yeah, yeah)\r\n"
             				+ "You've got the feeling\r\n"
             				+ "Rock the other side\r\n"
             				+ "You've got the feeling (yeah, yeah)\r\n"
             				+ "You've got the feeling\r\n"
             				+ "Rock the other side\r\n"
             				+ "You've got the feeling (yeah, yeah)",
                             "hip hop",
                             "Dr. Dre ft. Snoop Dogg"));
             canciones.add((Cancion) new Cancion("Rapper's Delight",
             				"I said-a hip, hop, the hippie, the hippie\r\n"
             				+ "To the hip hip hop-a you don't stop the rock\r\n"
             				+ "It to the bang-bang boogie, say up jump the boogie\r\n"
             				+ "To the rhythm of the boogie, the beat"
             				+ "&&"
             				+ "Now what you hear is not a test: I'm rappin' to the beat\r\n"
             				+ "And me, the groove, and my friends are gonna try to move your feet\r\n"
             				+ "See, I am Wonder Mike, and I'd like to say hello\r\n"
             				+ "To the black, to the white, the red\r\n"
             				+ "And the brown, the purple and yellow\r\n"
             				+ "But first I gotta bang bang the boogie to the boogie\r\n"
             				+ "Say up jump the boogie to the bang bang boogie\r\n"
             				+ "Let's rock, you don't stop\r\n"
             				+ "Rock the riddle that will make your body rock\r\n"
             				+ "Well, so far you've heard my voice, but I brought two friends along\r\n"
             				+ "And next on the mike is my man Hank, come on Hank, sing that song"
             				+ "&&"
             				+ "Check it out, I'm the C-A-S-AN, the O-V-A and the rest is F-L-Y\r\n"
             				+ "You see, I go by the code of the doctor of the mix and these reasons I'll tell you why\r\n"
             				+ "You see I'm six foot one and I'm tons of fun and I dress to a D\r\n"
             				+ "You see I got more clothes than Muhammad Ali and I dress so viciously\r\n"
             				+ "I got bodyguards, I got two big cars, that definitely ain't the whack\r\n"
             				+ "I got a Lincoln continental and a sunroof Cadillac\r\n"
             				+ "So after school, I take a dip in the pool, which is really on the wall\r\n"
             				+ "I got a color TV so I can see the Knicks play basketball\r\n"
             				+ "Hear me talking 'bout checkbooks, credit cards, more money than a sucker could ever spend\r\n"
             				+ "But I wouldn't give a sucker or a bum from the Rucker, not a dime 'til I made it again"
             				+ "&&"
             				+ "Everybody go: Hotel, motel, whatcha gonna do today (Say what?)\r\n"
             				+ "'Cause I'ma get a fly girl, gonna get some spank and drive off in a def OJ\r\n"
             				+ "Everybody go: Hotel, motel, Holiday Inn\r\n"
             				+ "You see, if your girl starts acting up, then you take her friend"
             				+ "&&"
             				+ "Uh Master Gee, my mellow?\r\n"
             				+ "It's on you so what you gonna do?"
             				+ "&&"
             				+ "Well it's on and on and on, on and on\r\n"
             				+ "The beat don't stop until the break of dawn\r\n"
             				+ "I said a M-A-S, a T-E-R, a G with a double E\r\n"
             				+ "I said I go by the unforgettable name of the man they call the Master Gee"
             				+ "&&"
             				+ "Well, my name is known all over the world\r\n"
             				+ "By all the foxy ladies and the pretty girls\r\n"
             				+ "I'm going down in history\r\n"
             				+ "As the baddest rapper there ever could be"
             				+ "&&"
             				+ "Now I'm feeling the highs and you're feeling the lows\r\n"
             				+ "The beat starts getting into your toes\r\n"
             				+ "You start popping your fingers and stomping your feet\r\n"
             				+ "And moving your body while you're sitting in your seat\r\n"
             				+ "And then damn, you start doing the freak\r\n"
             				+ "I said damn, right outta your seat\r\n"
             				+ "Then you throw your hands high in the air\r\n"
             				+ "You're rocking to the rhythm, shake your derriere\r\n"
             				+ "Ya rockin' to the beat without a care\r\n"
             				+ "With the sureshot MCs for the affair\r\n"
             				+ "Now, I'm not as tall as the rest of the gang\r\n"
             				+ "But I rap to the beat just the same"
             				+ "&&"
             				+ "I got a little face, and a pair of brown eyes\r\n"
             				+ "All I'm here to do, ladies, is hypnotize\r\n"
             				+ "Singing on an' an' on an' on, on an' on\r\n"
             				+ "The beat don't stop until the break of dawn\r\n"
             				+ "Singing on an' an' on an' on, on an' on\r\n"
             				+ "Like a hot party the pop the pop the pop dibbie dibbie\r\n"
             				+ "Pop the pop, pop, you don't dare stop\r\n"
             				+ "Come alive y'all, gimme whatcha got\r\n"
             				+ "I guess by now you can take a hunch\r\n"
             				+ "And find that I am the baby of the bunch\r\n"
             				+ "But that's okay, I still keep in stride\r\n"
             				+ "'Cos all I'm here to do is just wiggle your behind\r\n"
             				+ "Singin' on'n'n'on'n'on n'on\r\n"
             				+ "The beat don't stop until the break of dawn\r\n"
             				+ "Singin' on'n'n'on'n'on on'n'on\r\n"
             				+ "Rock rock, y'all, throw it on the floor"
             				+ "&&"
             				+ "I'm gonna freak ya here I'm gonna freak you there\r\n"
             				+ "I'm gonna move you outta this atmosphere"
             				+ "&&"
             				+ "'Cos I'm one of a kind and I'll shock your mind\r\n"
             				+ "I'll put TNT tickin' in your behind\r\n"
             				+ "I said one, two, three, four, come on, girls, get on the floor\r\n"
             				+ "A-come alive, y'all, a-gimme whatcha got\r\n"
             				+ "'Cos I'm guaranteed to make you rock\r\n"
             				+ "I said one, two, three, four, tell me, Wonder Mike\r\n"
             				+ "What are you waiting for?"
             				+ "&&"
             				+ "I said a hip hop the hippie to the hippie\r\n"
             				+ "To the hip hip hop and you don't stop\r\n"
             				+ "The rock it to the bang bang the boogie\r\n"
             				+ "Say up jump the boogie, dig the rhythm of the boogie, the beat"
             				+ "&&"
             				+ "Skiddlee beebop a we rock a scooby doo\r\n"
             				+ "And guess what, America: we love you\r\n"
             				+ "'Cause ya rock and ya roll with so much soul\r\n"
             				+ "You could rock 'til you're a hundred and one years old\r\n"
             				+ "I don't mean to brag I don't mean to boast\r\n"
             				+ "But we like hot butter on a breakfast toast\r\n"
             				+ "Rock it up, uh, baby bubbah\r\n"
             				+ "Baby bubbah to the boogie the bang bang the boogie\r\n"
             				+ "To the beat beat, it's so unique\r\n"
             				+ "Come on, everybody, and dance to the beat"
             				+ "&&"
             				+ "A hip hop the hippie the hippie\r\n"
             				+ "To the hip hip hop and you don't stop\r\n"
             				+ "The rock it out baby boppa to the boogity bang bang\r\n"
             				+ "Boogie to the boogie, the beat"
             				+ "&&"
             				+ "I said I can't wait 'til the end of the week\r\n"
             				+ "When I'm rappin' to the rhythm of a groovy beat\r\n"
             				+ "An attempt to raise your body heat\r\n"
             				+ "Just blow your mind so that you can't speak\r\n"
             				+ "To do a thing but a rock and shuffle your feet\r\n"
             				+ "And let it change up to a dance called the freak\r\n"
             				+ "And when ya finally do come into your rhythmic beat\r\n"
             				+ "Rest a little while so ya don't get weak\r\n"
             				+ "I know a man named Hank\r\n"
             				+ "He has more rhymes than a serious bank\r\n"
             				+ "So come on Hank, uh, sing that song\r\n"
             				+ "To the rhythm of the boogie the bang bang the bong"
             				+ "&&"
             				+ "Well, I'm imp the dimp, the ladies pimp\r\n"
             				+ "The women fight for my delight\r\n"
             				+ "But I'm the grandmaster with the three MCs\r\n"
             				+ "That shock the house for the young ladies\r\n"
             				+ "And when you come inside, into the front\r\n"
             				+ "You do the freak, spank, and do the bump\r\n"
             				+ "And when the sucker MCs try to prove a point\r\n"
             				+ "We're treacherous trio, we're the serious joint\r\n"
             				+ "A-from sun-to-sun and from day-to-day\r\n"
             				+ "I sit down and write a brand new rhyme\r\n"
             				+ "Because they say that miracles never cease\r\n"
             				+ "I've created a devastating masterpiece\r\n"
             				+ "I'm gonna rock the mike 'til you can't resist\r\n"
             				+ "Everybody, I say, it goes like this\r\n"
             				+ "Well, I was comin' home late one dark afternoon\r\n"
             				+ "A reporter stopped me for a interview\r\n"
             				+ "She said she's heard stories and she's heard fables\r\n"
             				+ "That I'm vicious on the mic and the turntables\r\n"
             				+ "This young reporter, I did adore\r\n"
             				+ "So I rocked a vicious rhyme like I never did before\r\n"
             				+ "She said, \"Damn, fly guy, I'm in love with you!\r\n"
             				+ "The Casanova legend must have been true!\"\r\n"
             				+ "I said, \"By the way, baby, what's your name?\"\r\n"
             				+ "Said, \"I go by the name Lois Lane\r\n"
             				+ "And you could be my boyfriend, you surely can\r\n"
             				+ "Just let me quit my boyfriend called Superman\"\r\n"
             				+ "I said, \"He's a fairy, I do suppose\r\n"
             				+ "Flyin' through the air in pantyhose\r\n"
             				+ "He may be very sexy or even cute\r\n"
             				+ "But he looks like a sucker in a blue and red suit\""
             				+ "&&"
             				+ "I said, \"You need a man who's got finesse\r\n"
             				+ "And his whole name across his chest\r\n"
             				+ "He may be able to fly all through the night\r\n"
             				+ "But can he rock a party 'til the early light?\r\n"
             				+ "He can't satisfy you with his little worm\r\n"
             				+ "But I can bust you out with my super sperm!\""
             				+ "&&"
             				+ "I gon' do it, I gon' do it, I gon' do it, do it, do it\r\n"
             				+ "And I'm here, and I'm there, I'm Big Bank Hank, I'm everywhere\r\n"
             				+ "Just throw your hands up in the air\r\n"
             				+ "And party hardy like you just don't care\r\n"
             				+ "Let's do it, don't stop y'all\r\n"
             				+ "A-tick a-tock, y'all, you don't stop!\r\n"
             				+ "Go hotel, motel",
                             "hip hop",
                             "The Sugarhill Gang"));
             canciones.add((Cancion) new Cancion("California Love", 
             				"California love!"
             				+ "&&"
             				+ "California... knows how to party\r\n"
             				+ "California... knows how to party\r\n"
             				+ "In the citaaay of L.A.\r\n"
             				+ "In the citaaay of good ol' Watts\r\n"
             				+ "In the citaaay, the city of Compton"
             				+ "&&"
             				+ "We keep it rockin! We keep it rockin!"
             				+ "&&"
             				+ "We keep it rockin! We keep it rockin!"
             				+ "Now let me welcome everybody to the wild, wild west\r\n"
             				+ "A state that's untouchable like Elliot Ness\r\n"
             				+ "The track hits ya eardrum like a slug to ya chest\r\n"
             				+ "Pack a vest for your Jimmy in the city of sex\r\n"
             				+ "We in that sunshine state with a bomb ass hemp beat\r\n"
             				+ "The state where ya never find a dance floor empty\r\n"
             				+ "And pimps be on a mission for them greens\r\n"
             				+ "Lean mean money-makin-machines servin fiends\r\n"
             				+ "I been in the game for ten years makin rap tunes\r\n"
             				+ "Ever since honeys was wearin sassoon\r\n"
             				+ "Now it's '95 and they clock me and watch me\r\n"
             				+ "Diamonds shinin lookin like I robbed Liberace\r\n"
             				+ "It's all good, from Diego to tha Bay\r\n"
             				+ "Your city is tha bomb if your city makin pay\r\n"
             				+ "Throw up a finger if ya feel the same way"
             				+ "&&"
             				+ "Dre puttin it down for\r\n"
             				+ "Californ-i-a"
             				+ "&&"
             				+ "Shake it shake it baby\r\n"
             				+ "Shake it shake it baby\r\n"
             				+ "Shake it shake it mama"
             				+ "&&"
             				+ "Shake it Cali\r\n"
             				+ "Shake it shake it baby\r\n"
             				+ "Shake it shake it shake it shake it..."
             				+ "&&"
             				+ "Out on bail fresh outta jail, California dreamin\r\n"
             				+ "Soon as I stepped on the scene, I'm hearin hoochies screamin\r\n"
             				+ "&&"
             				+ "Fiendin for money and alcohol\r\n"
             				+ "The life of a west side playa where cowards die\r\n"
             				+ "Only in Cali where we riot not rally to live and die\r\n"
             				+ "In L.A. we wearin Chucks not Ballies (that's right)"
             				+ "&&"
             				+ "Dressed in Locs and khaki suits and ride is what we do\r\n"
             				+ "Flossin but have caution we collide with other crews\r\n"
             				+ "Famous cause we program worldwide\r\n"
             				+ "Let'em recognize from Long Beach to Rosecrans\r\n"
             				+ "Bumpin and grindin like a slow jam, it's west side\r\n"
             				+ "So you know the row won't bow down to no man\r\n"
             				+ "Say what you say\r\n"
             				+ "But give me that bomb beat from Dre\r\n"
             				+ "Let me serenade the streets of L.A.\r\n"
             				+ "From Oakland to Sacktown\r\n"
             				+ "The Bay Area and back down\r\n"
             				+ "Cali is where they put they mack down\r\n"
             				+ "Give me love!\r\n"
             				+ "Now make it shake..."
             				+ "&&"
             				+ "Uh, yeah, uh, longbeach in tha house, uh yeah\r\n"
             				+ "Oaktown, Oakland definately in tha house hahaha\r\n"
             				+ "Frisko, Frisko\r\n"
             				+ "Hey, you know LA is up in this\r\n"
             				+ "Pasadena, where you at"
             				+ "&&"
             				+ "Yeah, Inglewood, Inglewood always up to no good"
             				+ "&&"
             				+ "even Hollywood tryin to get a piece baby\r\n"
             				+ "Sacramento, sacramento where ya at? yeah\r\n"
             				+ "Throw it up y'all, throw it up, Throw it up\r\n"
             				+ "Let's show these fools how we do this on that west side\r\n"
             				+ "Cause you and I know it's tha best side\r\n"
             				+ "Yeah, That's riight\r\n"
             				+ "West coast, west coast\r\n"
             				+ "Uh, California Love\r\n"
             				+ "California Love",
             				"hip hop",
                             "2Pac ft. Dr. Dre"));
             canciones.add((Cancion) new Cancion("Gin and Juice",
                             "With so much drama in the L-B-C\r\n"
                             + "It's kinda hard being Snoop D-O-double-G\r\n"
                             + "But I, somehow, some way\r\n"
                             + "Keep comin' up with funky ass shit like every single day\r\n"
                             + "May I, kick a little something for the G's (yeah)\r\n"
                             + "And, make a few ends as (yeah!) I breeze, through\r\n"
                             + "Two in the mornin' and the party's still jumpin'\r\n"
                             + "Cause my momma ain't home\r\n"
                             + "I got bitches in the living room gettin' it on\r\n"
                             + "And, they ain't leavin til' six in the mornin' (six in the mornin')\r\n"
                             + "So what you wanna do, sheeeit\r\n"
                             + "I got a pocket full of rubbers and my homeboys do too\r\n"
                             + "So turn off the lights and close the doors\r\n"
                             + "But (but what?) we don't love them hoes, yeah!\r\n"
                             + "So we gonna smoke a ounce to this\r\n"
                             + "G's up, hoes down, while you motherfuckers bounce to this"
                             + "&&"
                             + "Rollin' down the street, smokin' indo, sippin' on gin and juice\r\n"
                             + "Laid back\r\n"
                             + "(With my mind on my money and my money on my mind)"
                             + "&&"
                             + "Rollin' down the street, smokin' indo, sippin' on gin and juice\r\n"
                             + "Laid back\r\n"
                             + "(With my mind on my money and my money on my mind)"
                             + "&&"
                             + "Now, that, I got me some Seagram's gin\r\n"
                             + "Everybody got they cups, but they ain't chipped in\r\n"
                             + "Now this types of shit, happens all the time\r\n"
                             + "You got to get yours but fool I gotta get mine\r\n"
                             + "Everything is fine when you listenin' to the D-O-G\r\n"
                             + "I got the cultivating music that be captivating he\r\n"
                             + "Who listens, to the words that I speak\r\n"
                             + "As I take me a drink to the middle of the street\r\n"
                             + "And get to mackin' to this bitch named Sadie (Sadie?)\r\n"
                             + "She used to be the homeboy's lady (Oh, that bitch)\r\n"
                             + "Eighty degrees, when I tell that bitch please\r\n"
                             + "Raise up off these N-U-T's, cause you gets none of these\r\n"
                             + "At ease, as I mob with the Dogg Pound, feel the breeze\r\n"
                             + "Beeeitch, I'm just"
                             + "&&"
                             + "Rollin' down the street, smokin' indo, sippin' on gin and juice\r\n"
                             + "Laid back\r\n"
                             + "(With my mind on my money and my money on my mind)"
                             + "&&"
                             + "Rollin' down the street, smokin' indo, sippin' on gin and juice\r\n"
                             + "Laid back\r\n"
                             + "(With my mind on my money and my money on my mind)"
                             + "&&"
                             + "Later on that day\r\n"
                             + "My homey Dr. Dre came through with a gang of Tanqueray\r\n"
                             + "And a fat ass J, of some bubonic chronic that made me choke\r\n"
                             + "Shit, this ain't no joke\r\n"
                             + "I had to back up off of it and sit my cup down\r\n"
                             + "Tanqueray and chronic, yeah I'm fucked up now\r\n"
                             + "But it ain't no stoppin', I'm still poppin'\r\n"
                             + "Dre got some bitches from the city of Compton\r\n"
                             + "To serve me, not with a cherry on top\r\n"
                             + "Cause when I bust my nut, I'm raisin' up off the cot\r\n"
                             + "Don't get upset girl, that's just how it goes\r\n"
                             + "I don't love you hoes, I'm out the do'\r\n"
                             + "And I'll be"
                             + "&&"
                             + "Rollin down the street, smokin' indo,\r\n"
                             + "Sippin' on gin and juice (beeotch!!)\r\n"
                             + "Laid back\r\n"
                             + "(With my mind on my money and my money on my mind)"
                             + "&&"
                             + "Rollin' down the street, smokin' indo,\r\n"
                             + "Sippin' on gin and juice (beeotch!!)\r\n"
                             + "Laid back\r\n"
                             + "(With my mind on my money and my money on my mind)",
                             "hip hop", "Snoop Dogg"));
             canciones.add((Cancion) new Cancion("Juicy",
             				"It was all a dream, I used to read Word Up! magazine\r\n"
             				+ "Salt-n-Pepa and Heavy D up in the limousine\r\n"
             				+ "Hangin' pictures on my wall\r\n"
             				+ "Every Saturday Rap Attack, Mr. Magic, Marley Marl\r\n"
             				+ "I let my tape rock 'til my tape popped\r\n"
             				+ "Smokin' weed in Bambú, sippin' on Private Stock\r\n"
             				+ "Way back, when I had the red and black lumberjack\r\n"
             				+ "With the hat to match\r\n"
             				+ "Remember Rappin' Duke? Duh-ha, duh-ha\r\n"
             				+ "You never thought that hip-hop would take it this far\r\n"
             				+ "Now I'm in the limelight 'cause I rhyme tight\r\n"
             				+ "Time to get paid, blow up like the World Trade\r\n"
             				+ "Born sinner, the opposite of a winner\r\n"
             				+ "Remember when I used to eat sardines for dinner\r\n"
             				+ "Peace to Ron G, Brucie B, Kid Capri\r\n"
             				+ "Funkmaster Flex, Lovebug Starski\r\n"
             				+ "I'm blowin' up like you thought I would\r\n"
             				+ "Call the crib, same number, same hood, it's all good\r\n"
             				+ "And if you don't know, now you know, nigga\r\n"
             				+ "[Chorus: Total & Puff Daddy]\r\n"
             				+ "You know very well (Yeah)\r\n"
             				+ "Who you are (Money, hoes and clothes)\r\n"
             				+ "Don't let 'em hold you down (Bankrolls, yeah, haha)\r\n"
             				+ "Reach for the stars (It's all good)\r\n"
             				+ "You had a goal (C'mon)\r\n"
             				+ "But not that many (It's all good)\r\n"
             				+ "'Cause you're the only one\r\n"
             				+ "I'll give you good and plenty (Check it)"
             				+ "&&"
             				+ "I made the change from a common thief\r\n"
             				+ "To up close and personal with Robin Leach\r\n"
             				+ "And I'm far from cheap, I smoke skunk with my peeps all day\r\n"
             				+ "Spread love, it's the Brooklyn way\r\n"
             				+ "The Moët and Alizé keep me pissy, girls used to diss me\r\n"
             				+ "Now they write letters 'cause they miss me\r\n"
             				+ "I never thought it could happen, this rapping stuff\r\n"
             				+ "I was too used to packing gats and stuff\r\n"
             				+ "Now honeys play me close like butter play toast\r\n"
             				+ "From the Mississippi down to the East Coast\r\n"
             				+ "Condos in Queens, indo for weeks\r\n"
             				+ "Sold out seats to hear Biggie Smalls speak\r\n"
             				+ "Living life without fear\r\n"
             				+ "Puttin' five karats in my baby girl ear\r\n"
             				+ "Lunches, brunches, interviews by the pool\r\n"
             				+ "Considered a fool 'cause I dropped out of high school\r\n"
             				+ "Stereotypes of a black male misunderstood\r\n"
             				+ "And it's still all good\r\n"
             				+ "And if you don't know, now you know, nigga\r\n"
             				+ "You might also like\r\n"
             				+ "The Grants\r\n"
             				+ "Lana Del Rey\r\n"
             				+ "All Of The Girls You Loved Before\r\n"
             				+ "Taylor Swift\r\n"
             				+ "Love Language\r\n"
             				+ "SZA\r\n"
             				+ "[Chorus: Total & Puff Daddy]\r\n"
             				+ "You know very well (C'mon)\r\n"
             				+ "Who you are (Bankrolls)\r\n"
             				+ "Don't let 'em hold you down (Clothes)\r\n"
             				+ "Reach for the stars (Mansions)\r\n"
             				+ "You had a goal\r\n"
             				+ "But not that many (It's all good)\r\n"
             				+ "'Cause you're the only one\r\n"
             				+ "I'll give you good and plenty ('94)"
             				+ "&&"
             				+ "Super Nintendo, Sega Genesis\r\n"
             				+ "When I was dead broke, man, I couldn't picture this\r\n"
             				+ "50-inch screen, money-green leather sofa\r\n"
             				+ "Got two rides, a limousine with a chauffeur\r\n"
             				+ "Phone bill about two G's flat\r\n"
             				+ "No need to worry, my accountant handles that\r\n"
             				+ "And my whole crew is loungin'\r\n"
             				+ "Celebrating every day, no more public housin'\r\n"
             				+ "Thinkin' back on my one-room shack\r\n"
             				+ "Now my mom pimps an Ac' with minks on her back\r\n"
             				+ "And she loves to show me off of course\r\n"
             				+ "Smiles every time my face is up in The Source\r\n"
             				+ "We used to fuss when the landlord dissed us\r\n"
             				+ "No heat, wonder why Christmas missed us\r\n"
             				+ "Birthdays was the worst days\r\n"
             				+ "Now we sip Champagne when we thirsty\r\n"
             				+ "Uh, damn right I like the life I live\r\n"
             				+ "'Cause I went from negative to positive and it's all (It's all good, nigga)\r\n"
             				+ "And if you don't know, now you know, nigga"
             				+ "&&"
             				+ "You know very well (Money)\r\n"
             				+ "Who you are (Hoes and clothes)\r\n"
             				+ "Don't let 'em hold you down (Bankrolls)\r\n"
             				+ "And if you don't know, now you know, nigga\r\n"
             				+ "Reach for the stars (That's right)\r\n"
             				+ "You had a goal (It's all good)\r\n"
             				+ "But not that many (All good)\r\n"
             				+ "'Cause you're the only one (East coast, represent)\r\n"
             				+ "I'll give you good and plenty (C'mon)\r\n"
             				+ "And if you don't know, now you know, nigga\r\n"
             				+ "\r\n"
             				+ "[Post-Chorus: The Notorious B.I.G. & Puff Daddy]\r\n"
             				+ "Representin' B-Town in the house (Biggie Smalls)\r\n"
             				+ "Junior Mafia, mad flavor (Bad Boy)\r\n"
             				+ "Uh, uh, yeah, aight (I see you, Cooch)\r\n"
             				+ "&&"
             				+ "You know very well (Money)\r\n"
             				+ "Who you are (Hoes and clothes)\r\n"
             				+ "Don't let 'em hold you down (Bankrolls)\r\n"
             				+ "And if you don't know, now you know, nigga\r\n"
             				+ "Reach for the stars (That's right)\r\n"
             				+ "You had a goal (It's all good)\r\n"
             				+ "But not that many (All good)\r\n"
             				+ "'Cause you're the only one (East coast, represent)\r\n"
             				+ "I'll give you good and plenty (C'mon)\r\n"
             				+ "And if you don't know, now you know, nigga\r\n"
             				+ "\r\n"
             				+ "[Post-Chorus: The Notorious B.I.G. & Puff Daddy]\r\n"
             				+ "Representin' B-Town in the house (Biggie Smalls)\r\n"
             				+ "Junior Mafia, mad flavor (Bad Boy)\r\n"
             				+ "Uh, uh, yeah, aight (I see you, Cooch)\r\n"
             				+ "&&"
             				+ "You know very well\r\n"
             				+ "Who you are\r\n"
             				+ "Don't let 'em hold you down\r\n"
             				+ "Reach for the stars\r\n"
             				+ "You had a goal\r\n"
             				+ "But not that many\r\n"
             				+ "'Cause you're the only one\r\n"
             				+ "I'll give you good and plenty",
                             "hip hop",
                             "The Notorious B.I.G."));

             // canciones de género "electrónica"
             canciones.add((Cancion) new Cancion("Levels", 
             				"Oh, sometimes\r\n"
             				+ "I get a good feeling, yeah\r\n"
             				+ "And a feeling that I never, never, never, never had before, no\r\n"
             				+ "I get a good feeling, yeah\r\n"
             				+ "&&"
             				+ "Oh, sometimes\r\n"
             				+ "I get a good feeling, yeah\r\n"
             				+ "And a feeling that I never, never, never, never had before, no\r\n"
             				+ "I get a good feeling, yeah",
             				"electrónica",
                             "Avicii"));
             canciones.add((Cancion) new Cancion("Strobe", 
             				"It's like a dream, you try to remember but it's gone",
                             "electrónica",
                             "Deadmau5"));
             canciones.add((Cancion) new Cancion("One More Time",
             				"One more time\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "One more time, we're gonna celebrate\r\n"
             				+ "Oh yeah, alright, don't stop the dancing\r\n"
             				+ "One more time, we're gonna celebrate\r\n"
             				+ "Oh yeah, alright, don't stop the dancing"
             				+ "&&"
             				+ "One more time, we're gonna celebrate\r\n"
             				+ "Oh yeah, alright, don't stop the dancing\r\n"
             				+ "One more time, we're gonna celebrate\r\n"
             				+ "Oh yeah"
             				+ "One more time"
             				+ "&&"
             				+ "One more time, we're gonna celebrate\r\n"
             				+ "Oh yeah, alright, don't stop the dancing\r\n"
             				+ "One more time, we're gonna celebrate\r\n"
             				+ "Oh yeah, alright, don't stop the dancing"
             				+ "&&"
             				+ "One more time, mmm\r\n"
             				+ "You know I'm just feelin'\r\n"
             				+ "Celebration\r\n"
             				+ "Tonight\r\n"
             				+ "Celebrate\r\n"
             				+ "Don't wait too late, mmm, no\r\n"
             				+ "We don't stop, you can't stop\r\n"
             				+ "We're gonna celebrate"
             				+ "&&"
             				+ "One more time\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "One more time, a celebration\r\n"
             				+ "You know we're gonna do it right\r\n"
             				+ "Tonight, hey, just feeling\r\n"
             				+ "Music's got me feeling the need\r\n"
             				+ "Need, yeah\r\n"
             				+ "Come on, alright"
             				+ "&&"
             				+ "We're gonna celebrate\r\n"
             				+ "One more time\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "Music's got me feeling so free\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free\r\n"
             				+ "One more time"
             				+ "&&"
             				+ "Music's got me feeling so free\r\n"
             				+ "We're gonna celebrate\r\n"
             				+ "Celebrate and dance so free",
                             "electrónica",
                             "Daft Punk"));
             canciones.add((Cancion) new Cancion("Adrenaline",
             				"Fuck all that funny jive"
             				+ "&&"
             				+ "Move through the night like truckers\r\n"
             				+ "When suckers see us they duck us, shit"
             				+ "&&"
             				+ "Fuck all that funny jive\r\n"
             				+ "Fuck all that funny jive\r\n"
             				+ "Fuck all that funny jive",
                             "electrónica",
                             "Zeds Dead"));
             canciones.add((Cancion) new Cancion("The Middle",
             				"Take a seat\r\n"
             				+ "Right over there, sat on the stairs\r\n"
             				+ "Stay or leave\r\n"
             				+ "The cabinets are bare, and I'm unaware"
             				+ "&&"
             				+ "Of just how we got into this mess, got so aggressive\r\n"
             				+ "I know we meant all good intentions"
             				+ "&&"
             				+ "So pull me closer\r\n"
             				+ "Why don't you pull me close?\r\n"
             				+ "Why don't you come on over?\r\n"
             				+ "I can't just let you go"
             				+ "&&"
             				+ "Oh baby\r\n"
             				+ "Why don't you just meet me in the middle?\r\n"
             				+ "I'm losing my mind just a little\r\n"
             				+ "So why don't you just meet me in the middle?\r\n"
             				+ "In the middle"
             				+ "&&"
             				+ "Baby\r\n"
             				+ "Why don't you just meet me in the middle?\r\n"
             				+ "I'm losing my mind just a little\r\n"
             				+ "So why don't you just meet me in the middle?\r\n"
             				+ "In the middle"
             				+ "&&"
             				+ "Ohh, take a step\r\n"
             				+ "Back for a minute, into the kitchen\r\n"
             				+ "Floors are wet\r\n"
             				+ "And taps are still runnin', dishes are broken"
             				+ "&&"
             				+ "How did we get into this mess? Got so aggressive\r\n"
             				+ "I know we meant all good intentions"
             				+ "&&"
             				+ "So pull me closer\r\n"
             				+ "Why don't you pull me close?\r\n"
             				+ "Why don't you come on over?\r\n"
             				+ "I can't just let you go"
             				+ "&&"
             				+ "Oh baby\r\n"
             				+ "Why don't you just meet me in the middle?\r\n"
             				+ "I'm losing my mind just a little\r\n"
             				+ "So why don't you just meet me in the middle?\r\n"
             				+ "In the middle"
             				+ "&&"
             				+ "Lookin' at you, I can't lie\r\n"
             				+ "Just pourin' out admission\r\n"
             				+ "Regardless of my objection, oh, oh\r\n"
             				+ "&&"
             				+ "And it's not about my pride\r\n"
             				+ "I need you on my skin\r\n"
             				+ "Just come over, pull me in, just"
             				+ "&&"
             				+ "Oh, baby\r\n"
             				+ "Why don't you just meet me in the middle?\r\n"
             				+ "I'm losing my mind just a little\r\n"
             				+ "So why don't you just meet me in the middle?\r\n"
             				+ "In the middle, no no"
             				+ "&&"
             				+ "Baby\r\n"
             				+ "Why don't you just meet me in the middle?\r\n"
             				+ "Oh yeah, I'm losing my mind just a little\r\n"
             				+ "So why don't you just meet me in the middle?\r\n"
             				+ "Oh, in the middle"
             				+ "&&"
             				+ "Baby\r\n"
             				+ "Why don't you just meet me in the middle, baby?\r\n"
             				+ "I'm losing my mind just a little\r\n"
             				+ "So why don't you just meet me in the middle, middle?\r\n"
             				+ "In the middle, middle",
                             "electrónica",
                             "Zedd, Maren Morris, Grey"));
     }
     
     public int size() {
 		return canciones.size();
 	 }
     
     public Cancion get(int index) {
 		return canciones.get(index);
 	}

     public List<Cancion> getCanciones() {
             return canciones;
     }

}